In [46]:
from IPython.display import display

import sys
import os
import pandas as pd
import numpy as np

sys.path.append(os.path.abspath("./"))
import helpers as _
#'explicit', 'danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo'

In [137]:
all_columns = ['uid', 'artist', 'artist_genre', 'album', 'album_year', 'track', 'track_genre', 'duration_ms', 'popularity', 
    'explicit', 'danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']

In [116]:
df_1 = pd.read_csv('Spotify/data/tracks_params_1.csv')
df_1

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [117]:
df_1.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

In [121]:
df_2 = pd.read_csv('Spotify/data/tracks_params_2.csv')
df_2.head()

,Track URI,Track Name,Artist URI(s),Artist Name(s),Album URI,Album Name,Album Artist URI(s),Album Artist Name(s),Album Release Date,Album Image URL,...,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature,Album Genres,Label,Copyrights
0,spotify:track:0vNPJrUrBnMFdCs8b2MTNG,Fader,spotify:artist:4W48hZAnAHVOC2c8WH8pcq,The Temper Trap,spotify:album:0V59MMtgoruvEqMv18KAOH,Conditions (Tour Edition),spotify:artist:4W48hZAnAHVOC2c8WH8pcq,The Temper Trap,2009,https://i.scdn.co/image/ab67616d0000b273f86ae8...,...,0.0353,0.000101,0.690000,0.0752,0.158,134.974,4.0,NaN,Liberation Records,"C 2010 Liberation Music, P 2010 Liberation Music"
1,spotify:track:0NpvdCO506uO58D4AbKzki,Sherry,spotify:artist:6mcrZQmgzFGRWf7C0SObou,Frankie Valli & The Four Seasons,spotify:album:0NUEQILaBzavnzcMEs4buZ,The Very Best of Frankie Valli & The 4 Seasons,spotify:artist:6mcrZQmgzFGRWf7C0SObou,Frankie Valli & The Four Seasons,2003-01-14,https://i.scdn.co/image/ab67616d0000b273b96c21...,...,0.0441,0.626000,0.000000,0.1130,0.734,117.562,4.0,NaN,Rhino,C © 2004 Bob Gaudio & Frankie Valli d/b/a The ...
2,spotify:track:1MtUq6Wp1eQ8PC6BbPCj8P,I Took A Pill In Ibiza - Seeb Remix,"spotify:artist:2KsP6tYLJlTBvSUxnwlVWa, spotify...","Mike Posner, Seeb",spotify:album:1Tz3Ai1guEFf4hV3d9i17K,"At Night, Alone.",spotify:artist:2KsP6tYLJlTBvSUxnwlVWa,Mike Posner,2016-05-06,https://i.scdn.co/image/ab67616d0000b273a19be7...,...,0.1110,0.035300,0.000008,0.0843,0.710,101.969,4.0,NaN,"Monster Mountain, LLC / Island","C © 2016 Island Records, a division of UMG Rec..."
3,spotify:track:59lq75uFIqzUZcgZ4CbqFG,Let Go for Tonight,spotify:artist:7qRll6DYV06u2VuRPAVqug,Foxes,spotify:album:5AQ7uKRSpAv7SNUl4j24ru,Glorious (Deluxe),spotify:artist:7qRll6DYV06u2VuRPAVqug,Foxes,2014-05-12,https://i.scdn.co/image/ab67616d0000b273ae5c7d...,...,0.0632,0.042900,0.000002,0.3260,0.299,140.064,4.0,NaN,Sign Of The Times Records,P (P) 2014 Sign Of The Times Limited under exc...
4,spotify:track:7KdcZQ3GJeGdserhK61kfv,The Way I Want To Touch You,spotify:artist:7BEfMxbaqx6dOpbtlEqScm,Captain & Tennille,spotify:album:3GUxesVyOehInaxJyCTh6d,Love Will Keep Us Together,spotify:artist:7BEfMxbaqx6dOpbtlEqScm,Captain & Tennille,1975-01-01,https://i.scdn.co/image/ab67616d0000b273e21a28...,...,0.0248,0.624000,0.000112,0.3430,0.597,111.290,4.0,NaN,A&M,"C © 1975 A&M Records, P This Compilation ℗ 197..."

In [122]:
df_2.columns

Index(['Track URI', 'Track Name', 'Artist URI(s)', 'Artist Name(s)',
       'Album URI', 'Album Name', 'Album Artist URI(s)',
       'Album Artist Name(s)', 'Album Release Date', 'Album Image URL',
       'Disc Number', 'Track Number', 'Track Duration (ms)',
       'Track Preview URL', 'Explicit', 'Popularity', 'ISRC', 'Added By',
       'Added At', 'Artist Genres', 'Danceability', 'Energy', 'Key',
       'Loudness', 'Mode', 'Speechiness', 'Acousticness', 'Instrumentalness',
       'Liveness', 'Valence', 'Tempo', 'Time Signature', 'Album Genres',
       'Label', 'Copyrights'],
      dtype='object')

In [123]:
df_2 = df_2.rename(columns={
    'Track URI': 'id',
    'Artist Genres': 'artist_genre',
    'Album Release Date': 'album_year',
    'Track Duration (ms)': 'duration_ms', 
    'Explicit': 'explicit',
    'Popularity': 'popularity',
    'Danceability': 'danceability',
    'Energy': 'energy',
    'Loudness': 'loudness',
    'Speechiness': 'speechiness',
    'Acousticness': 'acousticness',
    'Instrumentalness': 'instrumentalness',
    'Liveness': 'liveness',
    'Valence': 'valence',
    'Tempo': 'tempo'
})
df_2['id'] = df_2['id'].str.replace('spotify:track:', '')
df_2['album_year']=df_2['album_year'].str[0:4]

In [124]:
df_3 = pd.read_csv('Spotify/data/tracks_params_3.csv')
df_3.head()

,trackName,artistName,msPlayed,genre,danceability,energy,key,loudness,mode,speechiness,...,liveness,valence,tempo,type,id,uri,track_href,analysis_url,duration_ms,time_signature
0,"""Honest""",Nico Collins,191772,NaN,0.476,0.799,4.0,-4.939,0.0,0.2120,...,0.2570,0.577,162.139,audio_features,7dTxqsaFGHOXwtzHINjfHv,spotify:track:7dTxqsaFGHOXwtzHINjfHv,https://api.spotify.com/v1/tracks/7dTxqsaFGHOX...,https://api.spotify.com/v1/audio-analysis/7dTx...,191948.0,4.0
1,"""In The Hall Of The Mountain King"" from Peer G...",London Symphony Orchestra,1806234,british orchestra,0.475,0.130,7.0,-17.719,1.0,0.0510,...,0.1010,0.122,112.241,audio_features,14Qcrx6Dfjvcj0H8oV8oUW,spotify:track:14Qcrx6Dfjvcj0H8oV8oUW,https://api.spotify.com/v1/tracks/14Qcrx6Dfjvc...,https://api.spotify.com/v1/audio-analysis/14Qc...,150827.0,4.0
2,#BrooklynBloodPop!,SyKo,145610,glitchcore,0.691,0.814,1.0,-3.788,0.0,0.1170,...,0.3660,0.509,132.012,audio_features,7K9Z3yFNNLv5kwTjQYGjnu,spotify:track:7K9Z3yFNNLv5kwTjQYGjnu,https://api.spotify.com/v1/tracks/7K9Z3yFNNLv5...,https://api.spotify.com/v1/audio-analysis/7K9Z...,145611.0,4.0
3,$10,Good Morning,25058,experimental pop,0.624,0.596,4.0,-9.804,1.0,0.0314,...,0.1190,0.896,120.969,audio_features,3koAwrM1RO0TGMeQJ3qt9J,spotify:track:3koAwrM1RO0TGMeQJ3qt9J,https://api.spotify.com/v1/tracks/3koAwrM1RO0T...,https://api.spotify.com/v1/audio-analysis/3koA...,89509.0,4.0
4,(I Just) Died In Your Arms,Cutting Crew,5504949,album rock,0.625,0.726,11.0,-11.402,0.0,0.0444,...,0.0625,0.507,124.945,audio_features,4ByEFOBuLXpCqvO1kw8Wdm,spotify:track:4ByEFOBuLXpCqvO1kw8Wdm,https://api.spotify.com/v1/tracks/4ByEFOBuLXpC...,https://api.spotify.com/v1/audio-analysis/4ByE...,280400.0,4.0

In [125]:
df_3.columns

Index(['trackName', 'artistName', 'msPlayed', 'genre', 'danceability',
       'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'type', 'id', 'uri',
       'track_href', 'analysis_url', 'duration_ms', 'time_signature'],
      dtype='object')

In [126]:
df_3 = df_3.rename(columns={
    'genre': 'track_genre'
})

In [128]:
df_tracks = pd.read_csv('Spotify/data/Streaming_tracks.csv')

In [130]:
df_1_merged = pd.merge(df_tracks, df_1, left_on="uid", right_on="track_id", how="left")

In [132]:
df_1_merged.columns

Index(['uid', 'artist', 'artist_genre', 'album', 'album_year', 'track',
       'track_genre_x', 'duration_ms_x', 'popularity_x', 'explicit_x',
       'danceability_x', 'energy_x', 'loudness_x', 'speechiness_x',
       'acousticness_x', 'instrumentalness_x', 'liveness_x', 'valence_x',
       'tempo_x', 'Unnamed: 0', 'track_id', 'artists', 'album_name',
       'track_name', 'popularity_y', 'duration_ms_y', 'explicit_y',
       'danceability_y', 'energy_y', 'key', 'loudness_y', 'mode',
       'speechiness_y', 'acousticness_y', 'instrumentalness_y', 'liveness_y',
       'valence_y', 'tempo_y', 'time_signature', 'track_genre_y'],
      dtype='object')

In [134]:
columns = ['track_genre', 'duration_ms', 'popularity', 'explicit',
           'danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']

for column in columns:
    df_1_merged[column] = np.where(df_1_merged[f'{column}_x'].isnull() , df_1_merged[f'{column}_y'], df_1_merged[f'{column}_x'])
    df_1_merged = df_1_merged.drop(columns=[f'{column}_x', f'{column}_y'])

df_1_merged = df_1_merged[all_columns]

In [140]:
df_2_merged = pd.merge(df_1_merged, df_2, left_on="uid", right_on="id", how="left")

In [141]:
df_2_merged.columns

Index(['uid', 'artist', 'artist_genre_x', 'album', 'album_year_x', 'track',
       'track_genre', 'duration_ms_x', 'popularity_x', 'explicit_x',
       'danceability_x', 'energy_x', 'loudness_x', 'speechiness_x',
       'acousticness_x', 'instrumentalness_x', 'liveness_x', 'valence_x',
       'tempo_x', 'id', 'Track Name', 'Artist URI(s)', 'Artist Name(s)',
       'Album URI', 'Album Name', 'Album Artist URI(s)',
       'Album Artist Name(s)', 'album_year_y', 'Album Image URL',
       'Disc Number', 'Track Number', 'duration_ms_y', 'Track Preview URL',
       'explicit_y', 'popularity_y', 'ISRC', 'Added By', 'Added At',
       'artist_genre_y', 'danceability_y', 'energy_y', 'Key', 'loudness_y',
       'Mode', 'speechiness_y', 'acousticness_y', 'instrumentalness_y',
       'liveness_y', 'valence_y', 'tempo_y', 'Time Signature', 'Album Genres',
       'Label', 'Copyrights'],
      dtype='object')

In [143]:
columns = ['artist_genre', 'album_year', 'duration_ms', 'popularity', 'explicit',
           'danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']

for column in columns:
    df_2_merged[column] = np.where(df_2_merged[f'{column}_x'].isnull() , df_2_merged[f'{column}_y'], df_2_merged[f'{column}_x'])
    df_2_merged = df_2_merged.drop(columns=[f'{column}_x', f'{column}_y'])

KeyError: 'artist_genre_x'

In [144]:
df_2_merged = df_2_merged[all_columns]

In [146]:
df_3_merged = pd.merge(df_2_merged, df_3, left_on="uid", right_on="id", how="left")
df_3_merged

,uid,artist,artist_genre,album,album_year,track,track_genre_x,duration_ms_x,popularity,explicit,...,liveness_y,valence_y,tempo_y,type,id,uri,track_href,analysis_url,duration_ms_y,time_signature
0,1SYOjkkPEgoUFcqvAFzUkC,Noir Désir,NaN,Noir Desir En Public,NaN,Si Rien Ne Bouge,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1rONEDBEkebH436T1uSVTe,Noir Désir,NaN,Noir Desir En Public,NaN,Septembre En Attendant,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6P7wGICOuPLL8WKomBlqyR,Duffy,NaN,Good Morning England (The Boat That Rocked),NaN,Stay With Me Baby,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,76bIWqpWvdgRt19nTpoCVW,The Kinks,NaN,Good Morning England (The Boat That Rocked),NaN,All Day and All of the Night,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6SGpMifJv6k5M1ciOaeBR6,The Turtles,NaN,Good Morning England (The Boat That Rocked),NaN,Elenore,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55246,6KatXb78ydvl8WzFxjwO7P,Hospitality,NaN,Trouble,NaN,Inauguration,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55247,3N4EQNTo6j3GU7s9mRufBD,The Dig,NaN,Midnight Flowers,NaN,Animal Screams,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55248,4MSgoaK6rkoNWb28GS3AUL,Future Islands,NaN,In the Fall,NaN,Virgo Distracts,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55249,6KJN2Fq7r6uU0ksmObogUg,French Kicks,NaN,Swimming,NaN,All Our Weekends,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55250,6i1VewefsH1p9K68myrJoF,Blackbird Blackbird,NaN,Tangerine Sky,NaN,Feel It In My Bones,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [147]:
df_3_merged.columns

Index(['uid', 'artist', 'artist_genre', 'album', 'album_year', 'track',
       'track_genre_x', 'duration_ms_x', 'popularity', 'explicit',
       'danceability_x', 'energy_x', 'loudness_x', 'speechiness_x',
       'acousticness_x', 'instrumentalness_x', 'liveness_x', 'valence_x',
       'tempo_x', 'trackName', 'artistName', 'msPlayed', 'track_genre_y',
       'danceability_y', 'energy_y', 'key', 'loudness_y', 'mode',
       'speechiness_y', 'acousticness_y', 'instrumentalness_y', 'liveness_y',
       'valence_y', 'tempo_y', 'type', 'id', 'uri', 'track_href',
       'analysis_url', 'duration_ms_y', 'time_signature'],
      dtype='object')

In [148]:
columns = ['track_genre', 'duration_ms',
           'danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']

for column in columns:
    df_3_merged[column] = np.where(df_3_merged[f'{column}_x'].isnull() , df_3_merged[f'{column}_y'], df_3_merged[f'{column}_x'])
    df_3_merged = df_3_merged.drop(columns=[f'{column}_x', f'{column}_y'])

In [149]:
df_3_merged = df_3_merged[all_columns]

In [150]:
df_tracks[df_tracks['speechiness'].notnull()].shape[0] / df_tracks.shape[0] * 100

9.771001918745307

In [151]:
df_3_merged[df_3_merged['speechiness'].notnull()].shape[0] / df_3_merged.shape[0] * 100

20.703697670630397

In [101]:
df_merged.columns

Index(['uid', 'artist', 'album', 'track', 'track_genre', 'popularity_x',
       'explicit_x', 'id', 'Track Name', 'Artist URI(s)', 'Artist Name(s)',
       'Album URI', 'Album Name', 'Album Artist URI(s)',
       'Album Artist Name(s)', 'Album Image URL', 'Disc Number',
       'Track Number', 'Track Preview URL', 'explicit_y', 'popularity_y',
       'ISRC', 'Added By', 'Added At', 'artist_genre', 'Key', 'Mode',
       'Time Signature', 'album_genre', 'Label', 'Copyrights', 'duration_ms',
       'album_year', 'danceability', 'energy', 'loudness', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo'],
      dtype='object')

In [152]:
df_3_merged = df_3_merged[all_columns]
df_3_merged.to_csv('Spotify/data/Streaming_tracks.csv', index=False)

In [153]:
df_3_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55251 entries, 0 to 55250
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   uid               54701 non-null  object
 1   artist            54701 non-null  object
 2   artist_genre      3534 non-null   object
 3   album             54701 non-null  object
 4   album_year        3545 non-null   object
 5   track             54701 non-null  object
 6   track_genre       10903 non-null  object
 7   duration_ms       11440 non-null  float64
 8   popularity        10612 non-null  float64
 9   explicit          10612 non-null  object
 10  danceability      11439 non-null  float64
 11  energy            11439 non-null  float64
 12  loudness          11439 non-null  float64
 13  speechiness       11439 non-null  float64
 14  acousticness      11439 non-null  float64
 15  instrumentalness  11439 non-null  float64
 16  liveness          11439 non-null  float64
 17  valence           11439 non-null  float64
 18  tempo             11439 non-null  float64
dtypes: float64(11), object(8)
memory usage: 8.4+ MB