In [32]:
from datetime import datetime
from plotly.graph_objects import FigureWidget
from IPython.display import display
from ipywidgets import HBox, VBox, Box, fixed, interactive_output

import os
import sys
import csv
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
import plotly.graph_objects as go

sys.path.append(os.path.abspath("./"))
import helpers as _

In [2]:
df = pd.read_csv('Meteo/data/meteo_horaire_69_69029001_2023.csv')
df['DATE'] = pd.to_datetime(df['DATE'], format='%Y%m%d%H')

In [3]:
df

,POSTE,DATE,RR1,DRR1,HNEIGEF,NEIGETOT,T,TD,TN,HTN,...,TMER,VVMER,ETATMER,DIRHOULE,TLAGON,UV2,INS2,INFRAR2,DIR2,DIF2
0,69029001,2023-01-01 00:00:00,0.0,0.0,NaN,0.0,14.9,8.0,14.7,2302.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1,69029001,2023-01-01 01:00:00,0.0,0.0,NaN,0.0,14.8,7.8,14.7,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2,69029001,2023-01-01 02:00:00,0.0,0.0,NaN,0.0,14.9,7.0,14.7,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
3,69029001,2023-01-01 03:00:00,0.0,0.0,NaN,0.0,15.1,6.8,15.0,201.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
4,69029001,2023-01-01 04:00:00,0.0,0.0,NaN,0.0,15.1,7.1,15.0,329.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,69029001,2023-12-31 19:00:00,0.0,0.0,NaN,0.0,5.9,3.8,5.9,1854.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
8756,69029001,2023-12-31 20:00:00,0.0,0.0,NaN,0.0,5.0,3.0,4.8,1950.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
8757,69029001,2023-12-31 21:00:00,0.0,0.0,NaN,0.0,4.4,2.7,4.4,2057.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
8758,69029001,2023-12-31 22:00:00,0.0,0.0,NaN,0.0,4.4,2.9,4.3,2106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
8759,69029001,2023-12-31 23:00:00,0.0,0.0,NaN,0.0,3.9,2.5,3.7,2239.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [29]:
df_sorted = df[sorted(df.columns)]
df_sorted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 99 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   B1         8738 non-null   float64
 1   B2         3000 non-null   float64
 2   B3         1320 non-null   float64
 3   B4         0 non-null      float64
 4   C1         0 non-null      float64
 5   C2         0 non-null      float64
 6   C3         0 non-null      float64
 7   C4         0 non-null      float64
 8   CH         0 non-null      float64
 9   CL         0 non-null      float64
 10  CM         0 non-null      float64
 11  DATE       8760 non-null   datetime64[ns]
 12  DD         8720 non-null   float64
 13  DD2        0 non-null      float64
 14  DG         8759 non-null   float64
 15  DHUMEC     0 non-null      float64
 16  DHUMI40    8757 non-null   float64
 17  DHUMI80    8757 non-null   float64
 18  DIF        0 non-null      float64
 19  DIF2       0 non-null      float64
 20  DIR        0 non-null      float64
 21  DIR2       0 non-null      float64
 22  DIRHOULE   0 non-null      float64
 23  DRR1       8664 non-null   float64
 24  DVV200     8736 non-null   float64
 25  DXI        8710 non-null   float64
 26  DXI2       0 non-null      float64
 27  DXI3S      0 non-null      float64
 28  DXY        8707 non-null   float64
 29  ENTH       8758 non-null   float64
 30  ESNEIGE    0 non-null      float64
 31  ETATMER    0 non-null      float64
 32  FF         8745 non-null   float64
 33  FF2        0 non-null      float64
 34  FXI        8760 non-null   float64
 35  FXI2       0 non-null      float64
 36  FXI3S      8709 non-null   float64
 37  FXY        8707 non-null   float64
 38  GEOP       0 non-null      float64
 39  GLO        8760 non-null   int64
 40  GLO2       8736 non-null   float64
 41  HNEIGEF    0 non-null      float64
 42  HNEIGEFI1  0 non-null      float64
 43  HNEIGEFI3  0 non-null      float64
 44  HTN        8757 non-null   float64
 45  HTX        8757 non-null   float64
 46  HUN        8757 non-null   float64
 47  HUX        8757 non-null   float64
 48  HXI        8710 non-null   float64
 49  HXI2       0 non-null      float64
 50  HXI3S      8709 non-null   float64
 51  HXY        8707 non-null   float64
 52  INFRAR     0 non-null      float64
 53  INFRAR2    0 non-null      float64
 54  INS        8739 non-null   float64
 55  INS2       8736 non-null   float64
 56  N          4309 non-null   float64
 57  N1         5694 non-null   float64
 58  N2         3000 non-null   float64
 59  N3         1320 non-null   float64
 60  N4         0 non-null      float64
 61  NBAS       8738 non-null   float64
 62  NEIGETOT   8407 non-null   float64
 63  PMER       8758 non-null   float64
 64  PMERMIN    8756 non-null   float64
 65  POSTE      8760 non-null   int64
 66  PSTAT      8757 non-null   float64
 67  RR1        8735 non-null   float64
 68  SOL        7622 non-null   float64
 69  SOLNG      19 non-null     float64
 70  T          8758 non-null   float64
 71  T10        8756 non-null   float64
 72  T100       8756 non-null   float64
 73  T20        8756 non-null   float64
 74  T50        8756 non-null   float64
 75  TCHAUSSEE  8712 non-null   float64
 76  TD         8758 non-null   float64
 77  TLAGON     0 non-null      float64
 78  TMER       0 non-null      float64
 79  TN         8759 non-null   float64
 80  TN50       8758 non-null   float64
 81  TNSOL      8758 non-null   float64
 82  TSNEIGE    0 non-null      float64
 83  TSV        8758 non-null   float64
 84  TUBENEIGE  0 non-null      float64
 85  TW         8757 non-null   float64
 86  TX         8760 non-null   float64
 87  U          8760 non-null   int64
 88  UABS       8758 non-null   float64
 89  UN         8757 non-null   float64
 90  UV         0 non-null      float64
 91  UV2        0 non-null      float64
 92  UV_INDICE  0 non-null      float64
 93  UX         8757 non-null   float64
 94  VV         8738 non-null   float64
 95  VVMER      0 non-null      float64
 96  W1         0 non-null      float64
 97  W2         0 non-null      float64
 98  WW         8736 non-null   float64
dtypes: datetime64[ns](1), float64(95), int64(3)
memory usage: 6.6 MB

In [26]:
# PSTAT       : pression station
# T           : température sous abri instantanée (en °C)
# RR1         : quantité de précipitation (en mm)
# DRR1        : durée des précipitations (en mn)
# U           : humidité relative (en %)
# FF          : force du vent moyenné sur 10 mn
# N           : nébulosité totale (en octa)
# SOL         : état du sol sans neige 

df_filtered = df[['DATE', 'PSTAT','T', 'RR1', 'DRR1', 'U', 'FF', 'N', 'SOL', 'TSV', 'PMER']]
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    8760 non-null   datetime64[ns]
 1   PSTAT   8757 non-null   float64
 2   T       8758 non-null   float64
 3   RR1     8735 non-null   float64
 4   DRR1    8664 non-null   float64
 5   U       8760 non-null   int64
 6   FF      8745 non-null   float64
 7   N       4309 non-null   float64
 8   SOL     7622 non-null   float64
 9   TSV     8758 non-null   float64
 10  PMER    8758 non-null   float64
dtypes: datetime64[ns](1), float64(9), int64(1)
memory usage: 752.9 KB

In [18]:
df_filtered.sample(5)

,DATE,PSTAT,T,RR1,DRR1,U,FF,N,SOL,TSV,PMER
7306,2023-11-01 10:00:00,984.3,14.7,0.0,0.0,67,5.9,6.0,NaN,11.2,1008.0
7920,2023-11-27 00:00:00,992.6,0.5,0.0,0.0,92,1.6,8.0,NaN,5.8,1017.8
8301,2023-12-12 21:00:00,984.3,11.4,0.0,0.0,94,2.6,8.0,2.0,12.6,1008.3
8436,2023-12-18 12:00:00,1012.0,1.7,0.0,0.0,99,1.5,8.0,0.0,6.8,1037.6
6069,2023-09-10 21:00:00,992.6,21.5,0.0,0.0,53,1.3,NaN,0.0,13.6,1015.9

In [19]:
display(
    _.generate_box(
        children=[
            _.generate_widget_corr(df_filtered, 'Heatmap', df_filtered.columns, [])
        ],
        layout=_.box_layout
    )
)

Box(children=(FigureWidget({
    'data': [{'coloraxis': 'coloraxis',
              'hovertemplate': 'x: %{x}<b…

In [21]:
df_sample = df_filtered.sample(frac=0.02)

display(
    _.generate_box(
        children=_.generate_widget_scatter_all(df_sample, df_sample.columns, point=10, width=400, height=400),
        layout=_.box_layout
    )
)

Box(children=(FigureWidget({
    'data': [{'hovertemplate': 'DATE=%{x}<br>PSTAT=%{y}<extra></extra>',
        …

In [16]:
df_sample = df_filtered.sample(frac=0.02)

display(
    _.generate_box(
        children=_.generate_widget_scatter_all(df_sample, ['DATE', 'U', 'T', 'TSV'], point=10, width=400, height=400),
        layout=_.box_layout
    )
)

Box(children=(FigureWidget({
    'data': [{'hovertemplate': 'DATE=%{x}<br>U=%{y}<extra></extra>',
            …